# This Workflow is used to Provision the entire infrastructure for this project. 
# 
# To use this workflow, you must configure the following GHA Secrets:
# AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
# in two environments: dev and prod
#
# and then run the workflow from the UI
# 

name: AWS Infra Provisioning
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'     
        required: true
        default: 'dev'
        type: environment
  push:
    branches:
      - "*" # All branches
    paths:
      - 'terraform/**' # Only changes in the infra directory

jobs:
  core_infra_plan:
    name: Plan - Provision Core Infrastructure
    uses: ./.github/workflows/template-terraform-plan.yml
    with:
      environment: dev
      layer: core
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
      AWS_REGION: ${{ secrets.AWS_REGION_DEV }}

  core_infra_apply:
    name: Apply - Provision Core Infrastructure
    uses: ./.github/workflows/template-terraform-apply.yml
    needs: core_infra_plan
    with:
      environment: dev
      layer: core
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
      AWS_REGION: ${{ secrets.AWS_REGION_DEV }}


  demo_infra_apply:
    name: Apply - Provision Demo Infrastructure
    uses: ./.github/workflows/template-terraform-apply.yml
    needs: core_infra_apply
    with:
      environment: dev
      layer: apps/demo
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
      AWS_REGION: ${{ secrets.AWS_REGION_DEV }}


